Partial compilation fix for Barry Allen governor.
drivers/cpufreq/cpufreq_barry_allen.c:173:3: error: implicit declaration
of function 'get_cpu_idle_time' [-Werror=implicit-function-declaration]
get_cpu_idle_time(smp_processor_id(), error now disappear as
get_cpu_idle_time is defined into cpufreq_governor.h